### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by nodiscc** [qwinff/qwinff#18]
It would be nice to have qwinff in Debian repositories. Since someone apparently packaged it for Ubuntu I assume it would be quite easy to port the package to Debian.

**Comment by alexmyczko** [comment]
I just wanted to create one! But the Makefile clean: target is utterly broken, running 
rm -rf /bin/*
rm -rf /build/*

**Comment by lzh9102** [comment]
This might be caused by PWD not being set by the shell. Could you try changing [line 14 of Makefile](https://github.com/qwinff/qwinff/blob/bf86bb67a3f073888d3487b113cecd2410c38a55/Makefile#L14) to `PROJECT_ROOT=$(shell pwd)` and see if `make clean` is only removing the local building directories but not `/bin`, `/build`?

Meanwhile, I'm working on replacing the makefile with cmake. Hopefully switching to cmake will make the building process more portable across platforms.

**Comment by alexmyczko** [comment]
I guess this issue can be closed, it's been in Debian officially for a while...

**Comment by nodiscc** [comment]
https://packages.debian.org/search?keywords=qwinff
